# Generated by Django 5.0.4 on 2024-04-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rarity', models.CharField(max_length=255)),
                ('essential', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('item_location', models.CharField(max_length=255)),
                ('image_filename', models.CharField(max_length=255)),
            ],
        ),
    ]
