# Generated by Django 5.0.4 on 2024-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_image_filename_items_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image_file',
            field=models.FileField(upload_to='assets/items'),
        ),
    ]
