# Generated by Django 5.0.4 on 2024-04-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_items_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image_file',
            field=models.FileField(upload_to='frontend/static/assets/items'),
        ),
    ]
