# Generated by Django 5.0.4 on 2024-04-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_items_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='rarity',
            field=models.CharField(max_length=255),
        ),
    ]
