# Generated by Django 5.0.4 on 2024-04-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_items_essential'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='essential',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='rarity',
            field=models.CharField(choices=[(0, 'Bronze'), (1, 'Silver'), (2, 'Gold')], max_length=255),
        ),
    ]
