# Generated by Django 5.0.4 on 2024-04-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_items_essential_alter_items_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='essential',
        ),
    ]
