# Generated by Django 5.0.4 on 2024-04-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_items_essential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='rarity',
            field=models.CharField(max_length=255),
        ),
    ]
